[tox]
env_list =
    py3
minversion = 4.21.2

[testenv]
description = run the tests with pytest
package = wheel
wheel_build_env = .pkg
passenv =
    # This allows tox environment on a DevBox to trigger host browser
    DISPLAY
deps =
    pytest>=6
    -r requirements.txt
commands =
    pip list
    {posargs:pytest --color=yes}

[testenv:azcli]
deps =
    azure-cli
commands_pre =
    # It will unfortunately be run every time but luckily subsequent runs are fast.
    pip install -e .
commands =
    pip list
    {posargs:az --version}
