[tox]
env_list =
    # Historically, this tox.ini is intended only for MSAL maintainer
    # to manually test with the whatever Python 3 version available on their devbox.
    # This way, it is unnecessary to enumerate all Python versions here.
    py3
minversion = 4.21.2

[testenv]
description = run the tests with pytest
package = wheel
wheel_build_env = .pkg
passenv =
    # This allows tox environment on a DevBox to trigger host browser
    DISPLAY
deps =
    pytest>=6
    -r requirements.txt
commands =
    pip list
    {posargs:pytest --color=yes}

[testenv:docs]
deps =
    -r docs/requirements.txt
commands =
    sphinx-build docs docs/_build

[testenv:azcli]
deps =
    azure-cli
commands_pre =
    # It will unfortunately be run every time but luckily subsequent runs are fast.
    pip install -e .
commands =
    pip list
    {posargs:az --version}
