name: Feature request
description: Suggest a new feature for MSAL Python.
labels: ["feature request", "untriaged", "needs attention"]
title : '[Feature Request] '
body:
- type: markdown
  attributes:
    value: |
      ## Before submitting your feature request
      Please make sure that your question or issue is not already covered in [MSAL documentation](https://learn.microsoft.com/entra/msal/python/) or [samples](https://learn.microsoft.com/azure/active-directory/develop/sample-v2-code?tabs=apptype).
      
- type: markdown
  attributes:
    value: |
      ## Feature request for MSAL Python
      
- type: dropdown
  attributes:
    label: MSAL client type
    description: Are you using Public Client (desktop apps, CLI apps) or Confidential Client (web apps, web APIs, service-to-service, managed identity)?
    multiple: true
    options: 
      - "Public"
      - "Confidential"      
  validations:
    required: true

- type: textarea
  attributes:
    label: Problem Statement
    description: "Describe the problem or context for this feature request."
  validations: 
    required: true

- type: textarea
  attributes:
    label: Proposed solution
    description: "Describe the solution you'd like."
  validations: 
    required: false
