#################################################################################
#                         OneBranch Pipelines - Official and CI                 #
# This pipeline was created by EasyStart from a sample located at:              #
#   https://aka.ms/obpipelines/easystart/samples                                #
# Documentation:  https://aka.ms/obpipelines                                    #
# Yaml Schema:    https://aka.ms/obpipelines/yaml/schema                        #
# Retail Tasks:   https://aka.ms/obpipelines/tasks                              #
# Support:        https://aka.ms/onebranchsup                                   #
#################################################################################

trigger: none # https://aka.ms/obpipelines/triggers

parameters: # parameters are shown up in ADO UI in a build queue time
  - name: 'debug'
    displayName: 'Enable debug output'
    type: boolean
    default: false

variables:
  CDP_DEFINITION_BUILD_COUNT: $[counter('', 0)] # needed for onebranch.pipeline.version task https://aka.ms/obpipelines/versioning
  system.debug: ${{ parameters.debug }}
  ENABLE_PRS_DELAYSIGN: 1
  ROOT: $(Build.SourcesDirectory)
  REPOROOT: $(Build.SourcesDirectory)
  OUTPUTROOT: $(REPOROOT)\out
  NUGET_XMLDOC_MODE: none

  WindowsContainerImage: 'onebranch.azurecr.io/windows/ltsc2022/vse2022:latest' # https://aka.ms/obpipelines/containers

resources:
  repositories:
    - repository: 1ESPipelineTemplates
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    settings:
      skipBuildTagsForGitHubPullRequests: true
    sdl:
      git:
        longpaths: true
        submodules: false
      sourceRepositoriesToScan:
        include:
        - repository: self
          submodule: false
        runInSingleJob: true
      #sourceAnalysisPool:
      #  name: azsdk-pool-mms-win-2022-general
      #  image: azsdk-pool-mms-win-2022-1espt
      #  os: windows
      sourceAnalysisPool:
        name: AzurePipelines-EO
        image: 1ESPT-windows2022
        os: windows
      eslint:
        enabled: false
        justificationForDisabling: "ESLint injected task has failures because it uses an old version of mkdirp. We should not fail for tools not controlled by the repo. See: https://dev.azure.com/azur     19 e-sdk/internal/_build/results?buildId=3556850"
      codeql:
        compiled:
          enabled: false
          justificationForDisabling: "CodeQL times our pipelines out by running for 2+ hours before being force canceled."
      psscriptanalyzer:
        compiled: true
        break: true
      policy: M365

    stages:
      - stage: build
        jobs:
          - job: main
            timeoutInMinutes: 120
            pool:
              type: windows  # read more about custom job pool types at https://aka.ms/obpipelines/yaml/jobs

            steps:
              - checkout: self
                submodules: false

              - script: |
                  python -m pip install build --user
                  python -m build --sdist --wheel --outdir "$(Build.ArtifactStagingDirectory)" .

              - task: EsrpRelease@7
                inputs:
                  DisplayName: 'Publish to PyPI'
                  ConnectedServiceName: 'AuthSdkResourceManager'
                  KeyVaultName: 'buildautomation'
                  AuthCertName: 'MSALJava-ESRP-Release-Auth-PrivateCA'
                  SignCertName: 'MSALJava-ESRP-Release-Sign-PublicCA'
                  ClientId: 'b8d01fe0-7a50-4af7-abce-571ec99e87a0'
                  Intent: 'PackageDistribution'
                  ContentType: 'PyPI'
                  ContentSource: 'Folder'
                  FolderLocation: '$(Build.ArtifactStagingDirectory)/dist'
                  waitforreleasecompletion: true
                  Owners: 'nugetaad@microsoft.com'
                  Approvers: 'rayluo@microsoft.com'
                  ServiceEndpointUrl: 'https://api.esrp.microsoft.com'
                  MainPublisher: 'ESRPRELPACMAN'
                  DomainTenantId: '72f988bf-86f1-41af-91ab-2d7cd011db47'

